replace mockito-all dependency with mockito-core due to a conflict
mockito-all conflicts with later hamcrest version since it's got the same class prepacked. More info here:
http://stackoverflow.com/questions/7869711/getting-nosuchmethoderror-org-hamcrest-matcher-describemismatch-when-running